name: http_exception
version: 1.0.0
description: A set of HTTP exceptions.
homepage: https://github.com/bwu-dart/http_exception
# authors:
#   - Günter Zöchbauer <guenter@gzoechbauer.com>
#   - Thomas Profelt <tom@octobyte.at>
#   - Diego Perez <eazel7@gmail.com>
#   - Andres Garcia <dev@tech-andgar.me>

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  http_status: ^3.2.0
  meta: ^1.12.0

dev_dependencies:
  test: ^1.17.12
  dart_code_linter: ^1.1.2
  lints: ^3.0.0
