name: http_exception
version: 0.2.2
description: A set of HTTP exceptions.
homepage: https://github.com/bwu-dart/http_exception
# authors:
#   - Günter Zöchbauer <guenter@gzoechbauer.com>
#   - Thomas Profelt <tom@octobyte.at>
#   - Diego Perez <eazel7@gmail.com>
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  http_status:
    git:
      url: https://github.com/andgar2010/http_status
      ref: 2.1.0

dev_dependencies:
  test: ^1.17.12
  dart_code_linter: ^1.1.2
  lints: ^3.0.0
