name: http_exception
version: 0.1.0
description: A set of HTTP exceptions.
homepage: https://github.com/bwu-dart/http_exception
authors:
  - Günter Zöchbauer <guenter@gzoechbauer.com>
  - Thomas Profelt <tom@octobyte.at>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:

dev_dependencies:
  grinder: '>=0.7.0-dev.1 <0.8.0'
  linter: '>=0.0.2 <0.1.0'
  analyzer: '>=0.24.0 <0.26.0'

